"""empty message

Revision ID: 478baf9b1717
Revises: None
Create Date: 2016-04-22 16:42:25.891396

"""

# revision identifiers, used by Alembic.
revision = '478baf9b1717'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('app', sa.String(length=8), nullable=True))
    op.add_column('client', sa.Column('checkbox', sa.String(length=8), nullable=True))
    op.add_column('client', sa.Column('reveal', sa.String(length=8), nullable=True))
    op.drop_column('client', 'rank')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('client', 'reveal')
    op.drop_column('client', 'checkbox')
    op.drop_column('client', 'app')
    ### end Alembic commands ###
