"""empty message

Revision ID: 8ad185f53865
Revises: 478baf9b1717
Create Date: 2016-04-22 16:47:57.582518

"""

# revision identifiers, used by Alembic.
revision = '8ad185f53865'
down_revision = '478baf9b1717'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'type')
    op.drop_column('client', 'app')
    op.drop_column('client', 'checkbox')
    op.drop_column('client', 'frequency')
    op.drop_column('client', 'amount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('checkbox', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('app', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('type', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    ### end Alembic commands ###
