"""empty message

Revision ID: 996d642e9126
Revises: b5fa88be812f
Create Date: 2016-04-22 20:31:20.216481

"""

# revision identifiers, used by Alembic.
revision = '996d642e9126'
down_revision = 'b5fa88be812f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'award', ['image'])
    op.create_unique_constraint(None, 'charity', ['image'])
    op.drop_constraint(u'achieved_award_fkey', 'achieved', type_='foreignkey')
    op.create_foreign_key(None, 'achieved', 'award', ['award'], ['image'])
    op.drop_constraint(u'donates_to_charity_fkey', 'donates_to', type_='foreignkey')
    op.create_foreign_key(None, 'donates_to', 'charity', ['charity'], ['image'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charity', type_='unique')
    op.drop_constraint(None, 'award', type_='unique')
    op.drop_constraint(None, 'donates_to', type_='foreignkey')
    op.create_foreign_key(u'donates_to_charity_fkey', 'donates_to', 'charity', ['charity'], ['name'])
    op.drop_constraint(None, 'achieved', type_='foreignkey')
    op.create_foreign_key(u'achieved_award_fkey', 'achieved', 'award', ['award'], ['name'])
    ### end Alembic commands ###
