"""empty message

Revision ID: b5fa88be812f
Revises: 8ad185f53865
Create Date: 2016-04-22 16:49:50.392968

"""

# revision identifiers, used by Alembic.
revision = 'b5fa88be812f'
down_revision = '8ad185f53865'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('app', sa.String(length=8), nullable=True))
    op.add_column('client', sa.Column('checkbox', sa.String(length=8), nullable=True))
    op.add_column('client', sa.Column('frequency', sa.String(length=8), nullable=True))
    op.add_column('client', sa.Column('type', sa.String(length=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'type')
    op.drop_column('client', 'frequency')
    op.drop_column('client', 'checkbox')
    op.drop_column('client', 'app')
    op.drop_column('client', 'amount')
    ### end Alembic commands ###
