"""Create FOBIAA Database

Revision ID: d8d128ba7088
Revises: None
Create Date: 2019-01-03 11:51:55.445629

"""

# revision identifiers, used by Alembic.
revision = 'd8d128ba7088'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('image', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('image')
    )
    op.create_table('charity',
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('image', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('image')
    )
    op.create_table('client',
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=24), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('reveal', sa.String(length=8), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=8), nullable=True),
    sa.Column('checkbox', sa.String(length=8), nullable=True),
    sa.Column('app', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('achieved',
    sa.Column('client', sa.String(length=16), nullable=False),
    sa.Column('award', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['award'], ['award.image'], ),
    sa.ForeignKeyConstraint(['client'], ['client.username'], ),
    sa.PrimaryKeyConstraint('client', 'award')
    )
    op.create_table('donates_to',
    sa.Column('client', sa.String(length=16), nullable=False),
    sa.Column('charity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['charity'], ['charity.image'], ),
    sa.ForeignKeyConstraint(['client'], ['client.username'], ),
    sa.PrimaryKeyConstraint('client', 'charity')
    )
    op.create_table('donation',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('client', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['client.username'], ),
    sa.PrimaryKeyConstraint('date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_table('donates_to')
    op.drop_table('achieved')
    op.drop_table('client')
    op.drop_table('charity')
    op.drop_table('award')
    ### end Alembic commands ###
